---
- name: Vector | Install rpm
  become: true
  ansible.builtin.yum:
    name: "{{ vector_url }}"
    state: present
  tags: vector
- name: Vector | Template config
  ansible.builtin.template:
    src: vector.yaml.j2
    dest: vector.yaml
    mode: 0644
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_gid }}"
    validate: vector validate --no-environment --config-yaml %s
  tags: vector
- name: Vector | Create systemd unit
  become: true
  ansible.builtin.template:
    src: vector.service.j2
    dest: /etc/systemd/system/vector.service
    mode: 0644
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_gid }}"
  tags: vector
- name: Vector | Start service
  become: true
  ansible.builtin.systemd:
    name: vector
    state: started
    daemon_reload: true
  ignore_errors: "{{ ansible_check_mode }}"
  tags: vector
